# Generated by Django 2.1.7 on 2019-03-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Childtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('childtask_id', models.BigIntegerField()),
                ('child_task_name', models.CharField(max_length=200)),
                ('schedule_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('created_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('userid', models.BigIntegerField()),
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=300)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('created_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='childtask',
            name='parent_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
    ]
