# Generated by Django 2.1.7 on 2019-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_childtask_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('taskid', models.BigIntegerField(null=True)),
                ('schedule_date', models.DateTimeField(null=True)),
                ('re_schedule_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reschedule',
            },
        ),
    ]
